# Generated by Django 4.2.7 on 2023-12-07 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_author', '0001_initial'),
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDescription', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('Task_Assign_Date', models.DateField(default=datetime.date.today)),
                ('Category', models.ManyToManyField(to='category_app.category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_author.author')),
            ],
        ),
    ]
